Makefile, gateware/arty.py, gateware/reader.py, gateware/writer.py, tests/test_reader.py, tests/test_writer.py
Separate BIST code from board file and add some tests for writer/reader modules.
=> Memory BIST improvements

rowhammer_tester/gateware/reader.py, rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/mem_bist.py, rowhammer_tester/scripts/utils.py, tests/test_reader.py
Use FPGA reader/writer modules to speed up rowhammer attack.
=> Use HW BIST to speed up rowhammer attack

rowhammer_tester/gateware/bist.py, rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/mem_bist.py, rowhammer_tester/scripts/rowhammer.py, rowhammer_tester/scripts/utils.py, tests/test_reader.py
This extends BIST Reader with CSRs to read the error value vs expected value, aside from error offset. 
It also changes the interface when using `skip_fifo=0`. Previously reader advanced to the next error on a read access from error_offset CSR. This is problematic due to https://github.com/antmicro/litex-rowhammer-tester/issues/22. Now it will it is required to write to error_continue CSR. Write access should not trigger the problem mentioned in the issue.
The scripts have been updated to use the new interface. The errors will be checked and the number of bitflips will be counted.
Example:
```
» python rowhammer_tester/scripts/hw_rowhammer.py --nrows 512 --read_count 0.8e6 --pattern 01_in_row --row-pairs const --const-rows-pair 3 343 --no-refresh                              
Using …
```
=> Improve BIST reader

rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/rowhammer.py
Using BIST and payload executor.
Notes:
There seems to be a bug somewhere, whereby I see errors in non-existent rows:
E.g.
python hw_rowhammer.py --pattern 01_per_row  --nrows 512 --read_count 10e6 --pattern 01_in_row --row-pairs const --const-rows-pair  $i $((i+2)) --payload-executor --no-refresh
...
Bit-flips for row     5: 3192
Bit-flips for row     7: 4169
Bit-flips for row     9: 2009
Bit-flips for row  4240: 1
Bit-flips for row  7043: 1
Bit-flips for row  7307: 1
Bit-flips for row  9950: 1
Bit-flips for row 16130: 1
Any help would be appreciated.
=> Hammer more than 2 rows

rowhammer_tester/gateware/payload_executor.py, rowhammer_tester/scripts/rowhammer.py
The biggest highlight is that it supports refreshes.  Some additional bug fixes are included.  See commit descriptions.
=> Improved payload (Attempt 3)

.git-blame-ignore-revs, .github/workflows/check-format.yml, .style.yapf, Makefile, requirements.txt, rowhammer_tester/payload/ddr3lib.py, rowhammer_tester/payload/ddr4lib.py, rowhammer_tester/payload/verify_payload.py, rowhammer_tester/scripts/analyzer.py, rowhammer_tester/scripts/etherbone_perf.py, rowhammer_tester/scripts/execute_payload.py, rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/mem.py, rowhammer_tester/scripts/mem_bist.py, rowhammer_tester/scripts/read_level.py, rowhammer_tester/scripts/rowhammer.py, rowhammer_tester/scripts/sim_runner.py, rowhammer_tester/scripts/utils.py
this PR adds `make format` target and runs formatting. The commit changing the format has been added to `.git-blame-ignore-file`
@jedrzejboczar @sqazi Please take a look at the formatting
=> Add make format and run formatiing

README.md
Clarifies that both mentioned FPGA boards are supported.
=> Fixes README: Supported FPGA boards (#42)

doc/requirements.txt, requirements.txt, rowhammer_tester/scripts/timestamp.py, rowhammer_tester/scripts/version.py, rowhammer_tester/targets/common.py
This will help us identify gateware version uploaded to the device.
=> common: add register containing git revision

doc/general.rst, rowhammer_tester/scripts/rowhammer.py
This PR updates description of commonly used scripts. It also contains a small fix for rowhammer.py.
=> doc: expand scripts chapter

rowhammer_tester/gateware/payload_executor.py, rowhammer_tester/scripts/utils.py, tests/test_payload_executor.py
This PR implements optional feature that allows to specify exact transition refresh command number (from start, as seen by RefreshCounter). It specifies the refresh at which the transition from Memory Controller to Payload Executor will take place. The feature is enabled via the [dfi_switch_at_refresh CSR](https://github.com/antmicro/litex-rowhammer-tester/blob/2926ab95d7ed5bf5999170e812c53d7b905a754c/rowhammer_tester/gateware/payload_executor.py#L338-L341). 
If `dfi_switch_at_refresh` it is set to 0, then the feature is disabled and we get the standard behavior: mode transition happens at the first refresh after the `payload_executor_start` CSR is written (to be exact, payload execution mode is active 1 cycle after the refresh has been sent on DFI). 
If `dfi_switch_at_refresh` CSR value …
=> Add option to transition to payload execution at specified refresh

.gitmodules, firmware/zcu104/etherbone/cmdline.c, firmware/zcu104/etherbone/cmdline.h, firmware/zcu104/etherbone/etherbone.c, firmware/zcu104/etherbone/etherbone.h, firmware/zcu104/etherbone/main.c, requirements.txt, rowhammer_tester/targets/arty.py, rowhammer_tester/targets/zcu104.py, third_party/xc3sprog.patch
This PR bumps all submodules to their latest versions. It also adds fix for Etherbone probe request in ZCU104's firmware.
=> Submodules bump

rowhammer_tester/targets/lpddr4_test_board.py
This PR bumps Litex ecosystem submodules to latest revisions. Litex/LiteDRAM/LiteEth have been rebased as they include patches needed for rowhammer-tester. 
With these updates it should now be possible to build rowhammer-tester for LPDDR4 Test Board with DRAM at 1000 MT/s using:
```
python rowhammer_tester/targets/lpddr4_test_board.py --sys-clk-freq 62.5e6 --iodelay-clk-freq 300e6 --load --build
```
or using the Makefile, e.g. `make ARGS="--sys-clk-freq 62.5e6 --iodelay-clk-freq 300e6" build`.
=> Bump submodules to include latest LPDDR4 DRAM training improvements

rowhammer_tester/targets/zcu104.py
With these changes IODELAYCTRL reference frequency is computed as a multiple of system clock frequency. This way there are no problems to find PLL config for a wide range of system frequencies. The default multiplier is `iodelay_clk_freq = 4*sys_clk_freq`, but it is auto-adjusted if the resulting frequency would fall outside of the range allowed for the device. This auto-scaling may not always lead to best DRAM leveling results, so if needed, the `--iodelay-clk-freq` command line argument can be used to force exact value.
=> targets/zcu104: automatically adjust iodelay clk frequency

doc/playbook.rst, rowhammer_tester/scripts/playbook/configs/example_half_double.json, rowhammer_tester/scripts/playbook/configs/example_half_double_analysis.json, rowhammer_tester/scripts/playbook/configs/example_hammer_tolerance_distance2.json, rowhammer_tester/scripts/playbook/payload_generators/half_double_analysis.py, rowhammer_tester/scripts/playbook/payload_generators/hammer_tolerance.py, rowhammer_tester/scripts/playbook/payload_generators/row_list.py, rowhammer_tester/scripts/playbook/playbook.py, rowhammer_tester/scripts/playbook/row_generators/__init__.py, rowhammer_tester/scripts/playbook/row_generators/half_double.py
There is a new payload generator that can be used to generate the tables used in our white paper.  We also added support in hammer tolerance payload generator to evaluate behaviour at higher distances.
These were tested with payload size of 0x100000.  What is the new procedure for adding documentation?
Please review and provide feedback.  Thanks :).
=> Patches related to half-double

rowhammer_tester/gateware/payload_executor.py, rowhammer_tester/scripts/playbook/lib/__init__.py, rowhammer_tester/targets/ddr4_datacenter_test_board.py
This PR is adds the DDR4 datacenter target.
=> Add DDR4 data center target

requirements.txt, rowhammer_tester/payload/ddr3lib.py, rowhammer_tester/payload/ddr4lib.py, rowhammer_tester/payload/verify_payload.py, rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/playbook/row_mappings/__init__.py, rowhammer_tester/scripts/read_level.py, rowhammer_tester/scripts/rowhammer.py, rowhammer_tester/scripts/utils.py
It fixes the check-format checks.
=> Fix formatting

doc/requirements.txt
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
=> docs: fix doc requirements and pin jinja version

doc/requirements.txt
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
=> docs: fix requirements

rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/rowhammer.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
=> hw_rowhammer: fix sequential rows attack

rowhammer_tester/scripts/hw_rowhammer.py, rowhammer_tester/scripts/rowhammer.py
The changes introduce the read_count_range parameter that can be used to start a set of rowhammer tests at once, that specifies a range of read_count value. Also, the error summary is now written to a json file if any bitflips occur.
=> Cell retention measurement modification

.github/workflows/test.yml, doc/general.rst
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>
=> Add information about row mapping and cell retention measurements

requirements.txt
Signed-off-by: Ryszard Różak <rrozak@antmicro.com>
=> Add pyvcd to pip requirements

doc/general.rst, requirements.txt, rowhammer_tester/scripts/mem_bist.py
Updated docs and requirements.txt to fix #108
=> Update listed dependencies.

doc/general.rst, rowhammer_tester/scripts/rowhammer.py
Currently user must run `mem.py` script manually to initialize memory. With this PR there is a DDR Controler status register checked to see whether memory is initialized or not. If it's not initialized, `mem.py` script is executed automatically.
=> Initialize memory automatically if not already initialized

rowhammer_tester/scripts/logs2plot.py
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>
=> Add max rows flag to logs2plot.py

doc/general.md
=> Sim doc improvements

rowhammer_tester/scripts/logs2vis.py
By passing `--no-empty-rows` flag one can generate a `json` output file that will generate a visualization by without empty rows.
This depends on chipsalliance/f4pga-database-visualizer/pull/8
=> logs2vis.py: Add support for omitting empty rows

rowhammer_tester/gateware/payload_executor.py, rowhammer_tester/scripts/decode_ddr5_dimms.py, rowhammer_tester/scripts/spd_eeprom.py, rowhammer_tester/targets/common.py, rowhammer_tester/targets/ddr5_test_board.py, rowhammer_tester/targets/ddr5_tester.py
This is a WIP PR adding DDR5 support in `spd_eeprom.py` script.
In order to get it working, I had to comment out memory controller itself and related modules, as it is not working correctly yet.
EEPROM holds 1024 bytes of data and reads are paged, 128 bytes each.
So to read we need to specify page number in MR11 register on 3 lowest bits for 8 pages total.
I added a `ddr5` switch to `read_spd` function, which value is being specified in `SPD_COMMANDS`.
When set, function loops over all pages and runs `i2c_read` command for each of them.
Because `parse_hexdump` asserts that each consecutive address is larger than the previous one I had to modify addresses from each read line by adding page number.
=> Add DDR5 support in spd_eeprom.py script

Makefile
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>
=> Build Verilator for simulation targets only

.gitmodules
This PR updates LiteDRAM and LiteX to versions with support for DDR timings configuration from software with module timings read from SPD.
Supersedes #137
=> Dynamic DDR timings

.gitmodules, requirements.txt
Remove litesdcard and litehyperbus submodules which are not used in the tester platform.
=> Submodule cleanup

.github/workflows/test.yml
Fixes sdram_test caused by a bug in the Refresher module.
Signed-off-by: Tomasz Michalak <tmichalak@antmicro.com>
=> Update litex and litedram submodules

rowhammer_tester/targets/zcu104.py
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>
=> Update zcu104 target's platform name

rowhammer_tester/scripts/spd_eeprom.py
In the current script, when the `mem_timeout` would run out, the script would just go to the `read_spd` function, as if memory init was done. That is incorrect.
Instead, wait until the `ddrctrl_init_done` is set regardless how long it would take.
I also increased the timeout for pexpect to 30 s as 6 s might be too low.
It should help with #144. Although, as there was a lot of debug information added to the BIOS, it will take a while to download the SPD contents when the memtest fails.
=> scripts/spd_eeprom: remove timeout for ddrctrl_init_done

Makefile, doc/general.md
Add help2man as a requirement, it is used by verilator Make verilator with `make deps` target
=> Update to newest Verilator version
