- rowhammer_tester/gateware/payload_executor.py
- rowhammer_tester/scripts/rowhammer.py
- rowhammer_tester/targets/common.py
- tests/test_payload_executor.py
Closes https://github.com/antmicro/litex-rowhammer-tester/issues/32.
This PR makes NOOP with `timeslice=0` be interpreted as STOP. Execution of STOP takes 1 cycle and terminates execution of payload. Timeslice is now interpreted as the exact number of cycles of instruction execution. It is invalid to use DFI instructions with timeslice=0. Generation of row-hammer payload has been updated to use the new timeslice interpretation and add STOP instruction.
If the [Encoder class](https://github.com/antmicro/litex-rowhammer-tester/blob/61b359ce2ada2223c534a2dbc6f297eae4b15abe/rowhammer_tester/gateware/payload_executor.py#L126) is used to define the payload, it will prevent such errors. It however does not perform full payload verification and it would be good to run the actual payload verifier …
> Add STOP instruction to terminate payload execution

- rowhammer_tester/scripts/rowhammer.py
Use the least common multiple between the number of rows
and the number of activates that fit in a single refresh interval.
If we put together this many activates and corresponding refreshes, we
should be able to loop them, since the sequence is repeatable without
violating the refresh contract.  This is better than the previous
approach of always refreshing when we cycle back to the first row
in the set.
Example:
(tREFI - rRFC)/(tRAS + tRP) = 116.
tREFW = 64ms = 8192 * tREFI
pick nr_aggressors = 2
So, choose read count of 116*8192 / nr_aggressors = 475136
This should yield ~8192 refreshes and ~64ms of execution time.
$ python hw_rowhammer.py  --nrows 10 --read_count 475136 --pattern 01_per_row --row-pairs const --const-rows-pair 0 2 --payload-executor  --data-inversion 2 0b10 …
> Reduce spurious refreshes in the payload

- rowhammer_tester/gateware/payload_executor.py
- rowhammer_tester/scripts/rowhammer.py
- rowhammer_tester/targets/common.py
- tests/test_payload_executor.py
This PR improves the moment of transition to payload execution and back. 
Now, after writing to the `start` CSR, Payload Executor will not immediately disconnect the memory controller, but will wait for a REFRESH command. This way the start of payload execution is well-defined in relation to DRAM timings. The first payload instruction is executed 2 clock cycles after the REF command, so the first payload instruction should be a NOOP with `timeslice=tRFC-2`. On the transition back, the refresh timer in memory controller gets reset, so first REF will be issued tREFI after finishing payload execution. I updated row-hammer payload generation in `rowhammer.py` to include the additional NOOP and REF.
Please take a look at this @sqazi and say if this is the way we want the transition to work.
> Synchronize mode transition to memory controller's REF command

- rowhammer_tester/gateware/payload_executor.py
The code should be equivalent.  However, we have a ZCU104 board where
the old implementation, for poorly explained reasons, leads to an
inability to initialize memory.  The new implementation does not appear
to have this issue.  Just to get past this hurdle, we make a minor change
to the implementation.
> Use mc_ongoing instead of ~pe_ongoing

- doc/development.rst
- doc/dram_modules.rst
- doc/general.rst
- doc/index.rst
- requirements.txt
- rowhammer_tester/scripts/spd_eeprom.py
- rowhammer_tester/targets/arty.py
- rowhammer_tester/targets/common.py
- rowhammer_tester/targets/zcu104.py
This PR adds support for reading SPD EEPROM on boards that use SO-DIMM DRAM modules (currently only ZCU104). SPD data is saved to a file and can then be used to calculate memory module parameters (timings/geometry). The file containing SPD data is passed using the `--form-spd` command line argument. Documentation has been updated with the instructions on how to read and use SPD data (please check `dram_modules.rst`). New python dependency is required (`pexpect`) so running `make python-deps` is required.
Currently we read SPD by sending commands on the LiteX BIOS console via UART crossover and parsing the output. This solution is sub-optimal, but currently LiteX lacks an I2C core and just uses software bitbanging. In the future we could add an I2C core to perform I2C operations using it's …
> Add support for using SPD EEPROM data

- .github/workflows/test.yml
- Makefile
- doc/general.rst
- rowhammer_tester/targets/common.py
- rowhammer_tester/targets/zcu104.py
This updates litex dependencies to include latest leveling improvements. The CRG for ZCU104 has been updated to match the version in litex-boards upstream. Additionally this PR adds an option to build with reloadable BIOS memory, which may be useful for debugging, and is now possible thanks to https://github.com/enjoy-digital/litex/commit/d0e8de077c7e3bff9dd4bbb4a8c683009550d264.
> Update LiteX/LiteDRAM dependecies

- rowhammer_tester/scripts/spd_eeprom.py
- rowhammer_tester/targets/ddr4_datacenter_test_board.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
This adds support to read the SPD data from the DIMMs on the datacenter board.
First the hex dump needs to be saved on a file:
```
python3 spd_eeprom.py read <output_file>
```
Than the same script can be used to show human readable values of the data
```
python3 spd_eeprom.py show <SPD data file> 100e6
```
The output of the last commands should be as follows:
```
_SDRAMModule:
clk_freq: 100000000.0
rate: 1:4
speedgrade: 3200
geom_settings: <litedram.common.GeomSettings object at 0x7f3c16fd6eb0>
timing_settings: <litedram.common.TimingSettings object at 0x7f3c16fd6e50>
memtype: DDR4
nbanks: 16
nrows: 131072
ncols: 1024
technology_timings: <litedram.modules._TechnologyTimings object at 0x7f3c16fd6fa0>
speedgrade_timings: {'3200': …
```
> Datacenter add I2C

- .github/workflows/check-format.yml
- .github/workflows/test.yml
- .gitignore
- doc/dram_modules.rst
- doc/general.rst
- doc/playbook.rst
- doc/zcu104.rst
- doc/zcu104_img.rst
- requirements.txt
- rowhammer_tester/gateware/bist.py
- rowhammer_tester/gateware/payload_executor.py
- rowhammer_tester/scripts/hw_rowhammer.py
- rowhammer_tester/scripts/rowhammer.py
- rowhammer_tester/targets/common.py
Added docstrings for `RowHammer` class and its methods.
Fixed some typos and bugs, as in title.
Last commit (pattern generation fix) also allows to hammer single row.
By using command below, one can hammer only row 31, 100 000 times.
```
python rowhammer_tester/scripts/hw_rowhammer.py --payload-executor --no-refresh --row-pairs const --const-rows-pair 31 31 --read_count 1e5
```
`hw_rowhammer.py` script must be used, as it fills and checks entire memory for bitflips, where non-hw version doesn't.
Payload executor is required as it bypasses DMA, which wouldn't deactivate row.
> Bug fixes and doc improvements

- doc/general.rst
- doc/playbook.rst
- rowhammer_tester/scripts/logs2dq.py
- rowhammer_tester/scripts/logs2plot.py
- rowhammer_tester/scripts/logs2vis.py
- rowhammer_tester/scripts/rowhammer.py
This PR is based on #69 and supersedes it.
Instead of overloading `rowhammer.py`, it extracts code used for generating plots and visualizations into separate scripts.
I had to extend generated logs a little bit to allow producing the same kinds of visualizations as in #69.
This allows visualizing on demand instead of only after an attack.
> Add scripts for visualizing attack results from logs

- rowhammer_tester/scripts/logs2dq.py
Add option to display results using logarithmic scale for Y axis when generating plots using `logs2dq.py`. This way when some DQ pads have much more errors, then resulting plot should be more readable.
Normal scale:
Log scale:
> Add logarithmic scale for DQ plots

- doc/general.rst
- rowhammer_tester/scripts/logs2plot.py
This PR adds support for plotting graphs to visualize which rows are affected by attacking single rows. It plots a graph with victims on X axis and aggressors on Y axis, tiles' colors correspond to amount of flipped bits. It also allows enabling labels with amount of bitflips that occured for specific rows.
Examples of outputs graphs after hammering 100 single rows with 100000 reads:
```bash
python hw_rowhammer.py --all-rows --nrows 100 --row-pair-distance 0 --payload-executor --no-refresh --read_count 1e5
```
1. Graph without annotations:
```bash
python logs2plot.py --aggressors-vs-victims logs.json
```
2. Graph with annotations:
```bash
python logs2plot.py --annotate bitflips --aggressors-vs-victims logs.json
```
> Visualize bit flips in rows by amount in relation to aggresor row

- rowhammer_tester/scripts/logs2dq.py
- rowhammer_tester/scripts/logs2plot.py
This adds a feature to open a new plot in new window that shows which DQs are affected by bitflips on a single aggressor vs victim attack log. New plots are opened each time user presses left mouse button on a tile that contains some logs. This will have no effect when pressed on empty tile or out of a graph bounds.
It works only for graphs that are generated for aggressors vs victims relations and it doesn't affect other variants.
Example of how it looks like:
> Generate DQ graphs for single aggressor vs victim log on mouse click

- rowhammer_tester/scripts/logs2vis.py
By applying a switch `--aggressors-vs-victims` with `logs2vis.py` this script will generate a json outputs that will allow one to visualize an aggressors against victims graph in F4PGA Database Visualizer.
It can be tested with chipsalliance/f4pga-database-visualizer/pull/8.
Below you can see an example of how it looks like:
> Add option to generate visualization for aggressors vs victims

- .gitmodules
This PR uses Antmicro's fork of Litex with some changes to litex client and server classes, which use EtherBone, aiming at adding verbosity and resilience of the UDP connection.
> submodules: Use Antmicro's Litex fork

- rowhammer_tester/targets/common.py
- rowhammer_tester/targets/ddr4_datacenter_test_board.py
This PR fixes issues with running simulation using `TARGET=ddr4_datacenter_test_board`
Added i2c pads to the sim and use `I2CMasterSim`.
Used correct pad names (`ddr4`, `lpddr4`) instead of `ddram`.
Fixes in LiteX for the wishbone arbiter and timeouts.
And fix in litedram for DDR4 simulation model.
> Rowhammer simulation fixes

- rowhammer_tester/scripts/analyzer.py
- rowhammer_tester/scripts/benchmark.py
- rowhammer_tester/scripts/bios_console.py
- rowhammer_tester/scripts/dump_regs.py
- rowhammer_tester/scripts/execute_payload.py
- rowhammer_tester/scripts/leds.py
- rowhammer_tester/scripts/mem.py
- rowhammer_tester/scripts/mem_bist.py
- rowhammer_tester/scripts/read_level.py
- rowhammer_tester/scripts/rowhammer.py
- rowhammer_tester/scripts/spd_eeprom.py
- rowhammer_tester/scripts/utils.py
- rowhammer_tester/scripts/version.py
This PR moves part of `version.py` body to separate function `read_ident` in `utils.py` so it can be used in other places as well.
In particular, I added `read_ident` call after each `wb.open()` in current scripts, so it is easier to share used configuration when copying console log.
<details>
<summary>
Example log. Notice board info in the second line of the output
</summary>
<p>
```
$ TARGET=ddr4_datacenter_test_board python rowhammer_tester/scripts/bios_console.py
Using generated target files in: build/ddr4_datacenter_test_board
Board info: Row Hammer Tester SoC on xc7k160tffg676-1, git: ae0efa3e328830c277e2f712c700bfbb48b0812f 2022-11-23 14:28:01
LiteX Crossover UART created: /dev/pts/6
Using serial backend: auto
picocom v3.1
port is        : /dev/pts/6
flowcontrol    : none
baudrate …
```
> Read ident

- .github/workflows/test.yml
- Makefile
- doc/general.md
- rowhammer_tester/scripts/benchmark.py
This PR adds `make pack` target, which allows to conveniently pack the bitstream with all required files for future use.
With such packed bitstream you don't need to have a RISC-V toolchain (and openocd is required only for flashing), so I created `minimal-deps` for such situations.
Regarding RISC-V toolchain, I modified `riscv64-unknown-elf-gcc` target, so it works like old `litex_setup.py gcc`, that is downloading a specific archive with the toolchain and using it.
The current method of using distro installed toolchain requires `sudo` privileges and means that different users will have different compiler versions depending on their distro, which may prove difficult when resolving issues.
Additionally, I added two small fixes:
- one in benchmark.py script which fixes an exception
- and …
> Add `make pack` target and some small fixes

- rowhammer_tester/targets/arty.py
Update target name for the Arty board after litex-boards update.
It was renamed from `arty` to `digilent_arty`
> Update target name for the Arty board

- rowhammer_tester/targets/common.py
This PR increases the default payload memory size to 32kB
> rowhammer_tester: Increase default payload memory size to 32kB

- doc/usage.md
- rowhammer_tester/targets/common.py
This PR adds an ability to perform memtest of RAM bypassing limitation of 32-bit address system bus.
It achieves this by usage of existing BIST modules from LiteX.
It also includes rebase of litex and litedram submodules on top of the current upstream master branches.
> Add sdram_hw_test using BIST modules from LiteX

- Makefile
Top name for zcu104 is xilinx_zcu104
Remove ddr5_tester target as DDR5 is not merged yet
Unindent TOP, OFL_BOARD assignments as well as an error if given target is unsupported.
Even though assignments can be indented and still work, the `$(error ...)` cannot be. If it is, `make` thinks it's a part of a recipe and errors with `recipe commences before first target`.
Signed-off-by: Michal Sieron <msieron@antmicro.com>
> Update board defines in the Makefile

- rowhammer_tester/targets/common.py
This is necessary to use the `sdram_hw_test` command.
> Build with litex bist by default

- firmware/zcu104/etherbone/etherbone.c
This PR fixes some issues with the zcu104:
- fixes inifinite loop on US(+) introduced in liblitedram_cleanup (this also contains litex bump)
- and etherbone server fix for #160
> zcu104 fixes

- rowhammer_tester/scripts/utils.py
This change updates `sdram_hardware_control` to work with DDR5 DFII.
Other memory standards should not be affected.
> Keep prevous flags in DFII control when switching to HW mode
